### PR TITLE
Support fpr PHPUnit 4.8/5.7 and Symfony 3.3/4.0

### PR DESCRIPTION
**Pull request by derrabus**
Greetings from #SymfonyConHackday2017.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I think you can go up-to PHP 7.0, as in other packages

**Comment by jaapio** [comment]
Thanks for this update. We will abandon this package when v3 of phpdocumentor is released. So I don't want anyone to spend to much time on this package.

**Comment by TomasVotruba** [comment]
I see. Well that might be one week or many years?

Thai should be noted somewhere in Readme or at better [deprecate the package](https://www.tomasvotruba.cz/blog/2017/07/03/how-to-deprecate-php-package-without-leaving-anyone-behind/)

**Comment by derrabus** [comment]
Abandoning this package would be fine for me, if newer releases of phpDocumentor won't depend on it anymore. So, should I rather try to get this dependency out of phpDocumentor itself or is somebody already working on that?

**Comment by jaapio** [comment]
I'm working on that, most of my time no is taken to add tests for the parts where this library is used. The code is hard to tests because everything is wrapped in a single class with way to much logic. 
You can follow my progress in https://github.com/phpDocumentor/phpDocumentor2/pull/1913

But I'm open for any support here. :-)

**Comment by mvriel** [comment]
It has been over 2 years without activity on this PR; given that this package is deprecated and the build fails I am closing this PR. I do want to apologize to @derrabus for this taking so long

**Comment by derrabus** [comment]
> I do want to apologize to @derrabus for this taking so long

No worries. 😃

**Pull request closed without merging**
